<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [351]:
import numpy as np

lista = [1,2,3,4,5,6,7,8,9]
array_unidimensional = np.array(lista)               
print(array_unidimensional)


[1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [352]:

array2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array2.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [353]:
listadada = [0,2,0,3,0,4,0]
array3 = np.array(listadada)
array3[array3 != 0] 

array([2, 3, 4])

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [354]:

array3x3 = np.random.randint(0,1,(3,3))
array3x3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [56]:
arrayaleatorio = np.random.randint(1,20,10)
arrayaleatorio
np.max(arrayaleatorio)
np.min(arrayaleatorio)
print(arrayaleatorio)
print(np.max(arrayaleatorio))
print(np.min(arrayaleatorio))

[17 16 11  7 12  4  6  2  4 16]
17
2


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [357]:
lista = [2,1,3,6,4,6,8,42,4,2]
array6 = lista[::-1]
array6


[2, 4, 42, 8, 6, 4, 6, 3, 1, 2]


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [69]:
arraytridimensional = np.random.randint(1,24,(2,3,4))
arraytridimensional
np.where(arraytridimensional[arraytridimensional == 15]) 
print(arraytridimensional)
print(np.where(arraytridimensional[arraytridimensional == 15]))

[[[16  5 18  5]
  [ 6 22  7 17]
  [ 7  4 20 12]]

 [[ 9 11  6 18]
  [13 10 23  8]
  [12 21  6  4]]]
(array([], dtype=int64),)


In [358]:
arraytridimensional[0]
arraytridimensional[1][2]

array([12, 21,  6,  4], dtype=int32)


#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [364]:
arraytridimensional2 = np.random.randint(1,30,(3,2,5))
arraytridimensional2

array([[[21, 29, 19, 12, 24],
        [22,  3,  3,  4, 23]],

       [[14, 18,  3,  4, 28],
        [13,  4, 17,  4, 16]],

       [[14,  2, 10, 17,  7],
        [22, 10, 29, 18, 18]]], dtype=int32)

In [368]:
arraytridimensional2[0, :, :2]
arraytridimensional2[1:3, :, :]


array([[[14, 18,  3,  4, 28],
        [13,  4, 17,  4, 16]],

       [[14,  2, 10, 17,  7],
        [22, 10, 29, 18, 18]]], dtype=int32)

#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [375]:
arraytridimensional3 = np.random.randint(1,24,(4,3,2))
print(arraytridimensional3)


[[[20  9]
  [ 8  5]
  [18  7]]

 [[22 14]
  [ 3 16]
  [20 16]]

 [[14  7]
  [ 4 20]
  [14  7]]

 [[23  6]
  [ 5  9]
  [ 4 16]]]


In [376]:
arraytridimensional3[1,1,:] = 0
print(arraytridimensional3)


[[[20  9]
  [ 8  5]
  [18  7]]

 [[22 14]
  [ 0  0]
  [20 16]]

 [[14  7]
  [ 4 20]
  [14  7]]

 [[23  6]
  [ 5  9]
  [ 4 16]]]


In [377]:
arraytridimensional3[3, :, :] = -1
arraytridimensional3


array([[[20,  9],
        [ 8,  5],
        [18,  7]],

       [[22, 14],
        [ 0,  0],
        [20, 16]],

       [[14,  7],
        [ 4, 20],
        [14,  7]],

       [[-1, -1],
        [-1, -1],
        [-1, -1]]], dtype=int32)


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [94]:
arraytridimensional4 = np.random.randint(-10,13,(2,4,3))
print(arraytridimensional4)
arraytridimensional4[arraytridimensional4 > 5] 



[[[-9  8 10]
  [ 3  5  9]
  [11  2  9]
  [-7  6 -8]]

 [[ 5  2 -9]
  [ 9 11 11]
  [-6 11 10]
  [-1 -2  2]]]


array([ 8, 10,  9, 11,  9,  6,  9, 11, 11, 11, 10], dtype=int32)

In [97]:
arraytridimensional4[arraytridimensional4 < 0] = 0
arraytridimensional4

array([[[ 0,  8, 10],
        [ 3,  5,  9],
        [11,  2,  9],
        [ 0,  6,  0]],

       [[ 5,  2,  0],
        [ 9, 11, 11],
        [ 0, 11, 10],
        [ 0,  0,  2]]], dtype=int32)

#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [382]:
arraytridimensional5 = np.random.randint(1,27,(3,3,3))


In [383]:
print(arraytridimensional5)



[[[11 12 23]
  [11  6  7]
  [23  7 25]]

 [[ 4  2 11]
  [15 21 19]
  [17  7 13]]

 [[23 20 18]
  [ 4 11 21]
  [ 5 26 23]]]


In [384]:
arraytridimensional5[1,:3,:2]

array([[ 4,  2],
       [15, 21],
       [17,  7]], dtype=int32)

In [385]:
arraytridimensional5[2][arraytridimensional5[2] > 20]


array([23, 21, 26, 23], dtype=int32)

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [468]:
array11 = np.random.randint(1,10,10)
array11
max = np.max(array11)
min= np.min(array11)
array11[array11 == max] = 0
array11[array11 == min] = 0
array11


array([0, 4, 6, 5, 0, 0, 0, 0, 5, 0], dtype=int32)

#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [269]:
array7 = np.random.randint(1,100,15)
array7


array([67, 72, 50, 25,  1, 77, 19, 81, 94,  4, 71, 82, 30, 42, 51],
      dtype=int32)

In [270]:
np.sort(array7)

array([ 1,  4, 19, 25, 30, 42, 50, 51, 67, 71, 72, 77, 81, 82, 94],
      dtype=int32)

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [273]:
array8 = np.random.randint(1,15,(1,4,4))
array8

array([[[14,  4,  6,  3],
        [14, 10,  4,  4],
        [ 9,  3,  5,  3],
        [ 7,  2,  8,  8]]], dtype=int32)

In [274]:
np.sum(array8)

np.int64(104)

#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [300]:
 unos = np.ones((5,5))
 unos[2,1:4]=0
 unos[1,1:4]=0
 unos[3,1:4]=0
 unos



array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [303]:
array9 = np.random.randint(1,15,10)
array9



array([ 2,  9,  1,  5,  9, 12,  5,  8,  1, 11], dtype=int32)

In [305]:
np.mean(array9)
np.std(array9)

np.float64(3.874274125562103)

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [320]:
array14 = np.random.randint(1,15,(2,3,4))
array14


array([[[ 6,  2,  5,  9],
        [ 1, 13,  6, 13],
        [12,  8,  6, 12]],

       [[13,  4,  8,  5],
        [ 7, 10, 10,  3],
        [ 5, 13,  1, 10]]], dtype=int32)

In [323]:
np.transpose(array14,(2,1,0)) 

array([[[ 6, 13],
        [ 1,  7],
        [12,  5]],

       [[ 2,  4],
        [13, 10],
        [ 8, 13]],

       [[ 5,  8],
        [ 6, 10],
        [ 6,  1]],

       [[ 9,  5],
        [13,  3],
        [12, 10]]], dtype=int32)

Teniamos un array de 2 matrices o arrays con 3 filas y 4 columnas y hemos pasado a un array con 4 matrices 3 filas y dos columnas

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [325]:
array15 = np.random.randint(1,24,(3,4,2))
array15

array([[[11, 16],
        [13,  5],
        [19,  1],
        [22, 20]],

       [[19, 20],
        [11, 20],
        [ 8, 18],
        [ 9, 17]],

       [[21, 10],
        [12, 21],
        [11,  8],
        [16, 16]]], dtype=int32)

In [330]:
np.transpose(array15,(2,0,1))

array([[[11, 13, 19, 22],
        [19, 11,  8,  9],
        [21, 12, 11, 16]],

       [[16,  5,  1, 20],
        [20, 20, 18, 17],
        [10, 21,  8, 16]]], dtype=int32)

#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [332]:
array16 = np.random.randint(1,24,(3,2,4))
array16

array([[[23,  5, 13, 15],
        [21, 16,  5, 18]],

       [[17, 12,  2, 20],
        [10,  6,  3, 19]],

       [[16, 17,  1, 10],
        [ 9, 13, 16,  1]]], dtype=int32)

In [333]:
np.transpose(array16,(2,0,1))

array([[[23, 21],
        [17, 10],
        [16,  9]],

       [[ 5, 16],
        [12,  6],
        [17, 13]],

       [[13,  5],
        [ 2,  3],
        [ 1, 16]],

       [[15, 18],
        [20, 19],
        [10,  1]]], dtype=int32)

#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [474]:
array17 = np.random.randint(-10,10,(3,4,5))
print(array17)
minimo = np.min(array17)
maximo = np.max(array17)
mediana =np.median(array17)

[[[ -1  -6  -1 -10   2]
  [  6   0  -5   6   8]
  [ -6 -10  -5  -1   0]
  [ -8 -10  -3   2  -1]]

 [[ -1   3   1  -5  -4]
  [ -8  -3  -8  -2  -4]
  [-10  -1   7  -3   3]
  [  2   7  -9  -3   7]]

 [[ -2   7   3  -1  -1]
  [ -9   2  -4   9  -3]
  [ -2  -5   3   8  -4]
  [  2   4   3   4   5]]]


In [480]:
arrayvacio =np.empty((3,4,5))

arrayvacio = np.where(array17 == maximo, "MAX", arrayvacio)
arrayvacio = np.where(array17 == minimo, "MIN", arrayvacio)
arrayvacio = np.where(array17 == mediana, "M", arrayvacio)
arrayvacio = np.where(array17 > mediana, "X", arrayvacio)
arrayvacio = np.where(array17 < mediana, "Y", arrayvacio)
arrayvacio

array([[['M', 'Y', 'M', 'Y', 'X'],
        ['X', 'X', 'Y', 'X', 'X'],
        ['Y', 'Y', 'Y', 'M', 'X'],
        ['Y', 'Y', 'Y', 'X', 'M']],

       [['M', 'X', 'X', 'Y', 'Y'],
        ['Y', 'Y', 'Y', 'Y', 'Y'],
        ['Y', 'M', 'X', 'Y', 'X'],
        ['X', 'X', 'Y', 'Y', 'X']],

       [['Y', 'X', 'X', 'M', 'M'],
        ['Y', 'X', 'Y', 'X', 'Y'],
        ['Y', 'Y', 'X', 'X', 'Y'],
        ['X', 'X', 'X', 'X', 'X']]], dtype='<U32')

#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [482]:
array18 = np.random.randint(1,24,(4,4))
array18

array([[18,  6,  5, 19],
       [20, 10, 14,  1],
       [ 2, 13, 13, 22],
       [ 4,  3, 13,  2]], dtype=int32)

In [508]:
filas = array18.shape[0]
columnas = array18.shape[1]
print(filas)
print(columnas)

hay_igualdad = False


for i in range(4):
    for j in range(4):
        Filasiguales = True
        for k in range(4): 
            if array18[i, k] != array18[k, j]:
                Filasiguales = False
                break
        
        if son_iguales:
            Filasiguales = True
            print('hay filas iguales')
            break
        else:
            print('No hay filas iguales')
            break

4
4
No hay filas iguales
No hay filas iguales
No hay filas iguales
No hay filas iguales
